FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y sqlite3

COPY sector_emissions_tool.py .
COPY ../utils.py ./utils.py
COPY ../sector_emissions.db ./sector_emissions.db

RUN pip install fastapi uvicorn

EXPOSE 8005

CMD ["uvicorn", "sector_emissions_tool:app", "--host", "0.0.0.0", "--port", "8005"]


